name       : haskell-base-compat
version    : 0.9.1
release    : 3
source     :
    - https://hackage.haskell.org/package/base-compat-0.9.1/base-compat-0.9.1.tar.gz : 1033b48146b9ffcf4f7c75a321ea0b1525c1b662230f46c41957a1b501b6464a
license    : MIT
component  : programming
summary    : Provides functions available in later versions of base to a wider range
    of compilers
description: |
    Provides functions available in later versions of base to a wider range of compilers
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
