name       : haskell-base-compat
version    : 0.10.1
release    : 4
source     :
    - https://hackage.haskell.org/package/base-compat-0.10.1/base-compat-0.10.1.tar.gz : b2ec2193d4a76a92c0ddcd69bb1b5879d50c98dd38422b0d86f85aea3112bb6d
license    : MIT
component  : programming
summary    : Provides functions available in later versions of base to a wider range of compilers
description: |
    Provides functions available in later versions of base to a wider range of compilers
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
