name       : haskell-base-compat
version    : 0.9.1
release    : 1
source     :
    - https://hackage.haskell.org/package/base-compat-0.9.1/base-compat-0.9.1.tar.gz : 1033b48146b9ffcf4f7c75a321ea0b1525c1b662230f46c41957a1b501b6464a
license    : MIT
component  : programming
summary    : Provides functions available in later versions of base to a wider range of compilers
description: |
    Provides functions available in later versions of base to a wider range of compilers
builddeps  :
    - ghc
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 base-compat-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/base-compat-$version.conf
