name       : haskell-base-compat
version    : 0.11.1
release    : 5
source     :
    - https://hackage.haskell.org/package/base-compat-0.11.1/base-compat-0.11.1.tar.gz : 356f1542ec93e7192a9073d32a8ef1e48194275495dcec7fb0d241f4baaf6d36
license    : MIT
component  : programming.haskell
summary    : Provides functions available in later versions of base to a wider range of compilers
description: |
    Provides functions available in later versions of base to a wider range of compilers
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
